### ISSUE TITLE
Projetar e criar o banco de dados dos funcionários, veículos e viagens.

### ISSUE THREAD

**Issue by viniciusRib** [BCC-UTFPR/Aplicativo_EngenhariaSoftware#1]

**Comment by fronchetti** [comment]
![imagedatabasemodel](https://cloud.githubusercontent.com/assets/15092904/14653547/d516f69e-064f-11e6-96cf-6d23588da328.png)
As tabelas e colunas foram definidas e o código .sql foi gerado.
O próximo passo será relacionar estas tabelas de acordo com o desenvolvimento do software.
