### ISSUE TITLE
Configurar o Hibernate.

### ISSUE THREAD

**Issue by viniciusRib** [BCC-UTFPR/Aplicativo_EngenhariaSoftware#4]

**Comment by MatheusRenato** [comment]
Tarefa finalizada, Criei o projeto no NetBeans, configurei o Hibernate, e adicionei os JAR's das bibliotecas na pasta Lib's.

**Comment by MatheusRenato** [comment]
Tarefa finalizada, Criei o projeto no NetBeans, configurei o Hibernate, e adicionei os JAR's das bibliotecas na pasta Lib's.
