### ISSUE TITLE
Criar classe de acesso ao Banco de Dados.

### ISSUE THREAD

**Issue by viniciusRib** [BCC-UTFPR/Aplicativo_EngenhariaSoftware#5]

**Comment by MatheusRenato** [comment]
Foram adicionados ao projeto as classes DAO, DAOInterface e EntityManagerProvider. 

DAO: possui os métodos para realizar as tarefas básica de um CRUD (inserir, alterar, deletar e selecionar);

EntityManagerProvider: é a classe que cria, gerencia e executa as transações no banco;

DAOInterface: como o próprio nome da classe indica ela é uma interface que tem o intuito de padronizar os métodos presente nas classes de database.
